### ISSUE TITLE
Proxyrack does not start

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#55]
The other day I bought some proxies and set them up and while I was at it, I added some more services.
All but proxyrack work. Checking the logs, proxyrack does not start because it's missing the UUID env. To one docker container, I added one manually. It starts now, however, there are more errors.

Not sure where to go from here. Is this an Issue with the script or an issue with the docker image of proxyrack?

Here's the log:

```
Please check your internet connection and try again.
Using provided UUID: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Updating Proxyrack...
--2023-10-08 08:45:39--  https://app-updates.sock.sh/peerclient/script/script.js
Resolving app-updates.sock.sh (app-updates.sock.sh)... 147.182.212.102
Connecting to app-updates.sock.sh (app-updates.sock.sh)|147.182.212.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1682231 (1.6M) [application/javascript]
Saving to: 'script.js'
     0K .......... .......... .......... .......... ..........  3%  157K 10s
    50K .......... .......... .......... .......... ..........  6%  387K 7s
   100K .......... .......... .......... .......... ..........  9% 1.21M 5s
   150K .......... .......... .......... .......... .......... 12%  543K 4s
   200K .......... .......... .......... .......... .......... 15% 2.46M 3s
   250K .......... .......... .......... .......... .......... 18% 11.2M 3s
   300K .......... .......... .......... .......... .......... 21% 1.33M 2s
   350K .......... .......... .......... .......... .......... 24%  429K 2s
   400K .......... .......... .......... .......... .......... 27% 25.8M 2s
   450K .......... .......... .......... .......... .......... 30%  718K 2s
   500K .......... .......... .......... .......... .......... 33% 2.66M 2s
   550K .......... .......... .......... .......... .......... 36% 1.97M 2s
   600K .......... .......... .......... .......... .......... 39%  555K 1s
   650K .......... .......... .......... .......... .......... 42%  252M 1s
   700K .......... .......... .......... .......... .......... 45%  267M 1s
   750K .......... .......... .......... .......... .......... 48% 1.43M 1s
   800K .......... .......... .......... .......... .......... 51% 6.95M 1s
   850K .......... .......... .......... .......... .......... 54% 36.6M 1s
   900K .......... .......... .......... .......... .......... 57%  251M 1s
   950K .......... .......... .......... .......... .......... 60%  250M 1s
  1000K .......... .......... .......... .......... .......... 63% 6.29M 1s
  1050K .......... .......... .......... .......... .......... 66%  250M 1s
  1100K .......... .......... .......... .......... .......... 70% 7.50M 0s
  1150K .......... .......... .......... .......... .......... 73%  260M 0s
  1200K .......... .......... .......... .......... .......... 76%  226M 0s
  1250K .......... .......... .......... .......... .......... 79%  256M 0s
  1300K .......... .......... .......... .......... .......... 82% 18.2M 0s
  1350K .......... .......... .......... .......... .......... 85%  259M 0s
  1400K .......... .......... .......... .......... .......... 88% 19.3M 0s
  1450K .......... .......... .......... .......... .......... 91% 37.7M 0s
  1500K .......... .......... .......... .......... .......... 94% 53.3M 0s
  1550K .......... .......... .......... .......... .......... 97% 25.2M 0s
  1600K .......... .......... .......... .......... ..        100%  196M=1.0s
2023-10-08 08:45:41 (1.56 MB/s) - 'script.js' saved [1682231/1682231]

Update done!
Error: ENOENT: no such file or directory, unlink '/Roaming/PoP/log.log'
    at Object.unlinkSync (fs.js:1136:3)
    at _0x2c25ab (/app/script.js:1:1676538)
    at _0x384958 (/app/script.js:1:1676778)
    at Object.<anonymous> (/app/script.js:1:1680542)
    at Object.<anonymous> (/app/script.js:1:1680605)
    at _0x34ba2d (/app/script.js:1:181281)
    at /app/script.js:1:182218
    at Object.<anonymous> (/app/script.js:1:182251)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {

  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/Roaming/PoP/log.log'
}
sending 
[Error: ENOENT: no such file or directory, open './go_version.txt'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './go_version.txt'
}
{ localVersion: '', remoteVersion: '56' }
downloading app
sending 
Error:  read ECONNRESET
Error:  read ECONNRESET
{ success: true }
sending 
writing 56 -> ./go_version.txt
written
go app started at: 1696754750
connecting to home: 1696754750
Error:  read ECONNRESET
connect failure: read tcp 198.18.0.1:47130->38.84.70.82:443: read: connection reset by peer
connected to home: 1696754755
Not Connected
connecting to home: 1696754756
connected to home: 1696754756
```

**Comment by engageub** [comment]
Thank you for raising this issue. Proxyrack docker was updated 19 days ago and their automated system for adding the host has been changed to manual. Changes are not required since the UUID has to be added manually before running the command. This will soon be updated. 

https://hub.docker.com/r/proxyrack/pop

Thank you

**Comment by engageub** [comment]
Changes pushed to branch https://github.com/engageub/InternetIncome/tree/main-proxyrack
Will be tested and deployed to main branch.

Thank you

**Comment by engageub** [comment]
Changes have been pushed to main branch. Please confirm if its working fine now.
Thank you

**Comment by copystring** [comment]
I'm trying just now. In the proxyrack.txt all UUID are after another without a new line. Can you have a look at this?

**Comment by engageub** [comment]
A separation has been added and updated. Please update it.

**Comment by copystring** [comment]
I'm sure it works. I'll take the UUID from the console for now. It takes a while to recreate all the docker containers

**Comment by copystring** [comment]
There are still errors in the containers:

```
Please check your internet connection and try again.
Using provided UUID: XXXXXXXXXXXXX
Updating Proxyrack...
--2023-10-08 21:06:25--  https://app-updates.sock.sh/peerclient/script/script.js
Resolving app-updates.sock.sh (app-updates.sock.sh)... 147.182.212.102
Connecting to app-updates.sock.sh (app-updates.sock.sh)|147.182.212.102|:443... connected.
Unable to establish SSL connection.

Update done!
internal/modules/cjs/loader.js:818

  throw err;
  ^
Error: Cannot find module '/app/script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by engageub** [comment]
Those errors are related to your connection. It mentions there is an issue with SSL connection not being established.
Is it working with direct connection and not working with proxy?
Please see the successful connection response. 
```
Updating Proxyrack...
--2023-10-08 21:12:37--  https://app-updates.sock.sh/peerclient/script/script.js
Resolving app-updates.sock.sh (app-updates.sock.sh)... 147.182.212.102
Connecting to app-updates.sock.sh (app-updates.sock.sh)|147.182.212.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
```

**Comment by copystring** [comment]
Yes, it's related to SSL and I'm using proxies. I tried without proxies and I get the same errors as before:

```
Please check your internet connection and try again.
Using provided UUID: XXXXXXXXXX
Updating Proxyrack...
--2023-10-08 21:23:19--  https://app-updates.sock.sh/peerclient/script/script.js
Resolving app-updates.sock.sh (app-updates.sock.sh)... 147.182.212.102
Connecting to app-updates.sock.sh (app-updates.sock.sh)|147.182.212.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1682231 (1.6M) [application/javascript]
Saving to: 'script.js'
     0K .......... .......... .......... .......... ..........  3%  239K 7s
    50K .......... .......... .......... .......... ..........  6%  492K 5s
   100K .......... .......... .......... .......... ..........  9% 6.86M 3s
   150K .......... .......... .......... .......... .......... 12%  645K 3s
   200K .......... .......... .......... .......... .......... 15% 1.87M 2s
   250K .......... .......... .......... .......... .......... 18% 13.6M 2s
   300K .......... .......... .......... .......... .......... 21% 7.50M 2s
   350K .......... .......... .......... .......... .......... 24% 7.15M 1s
   400K .......... .......... .......... .......... .......... 27%  618K 1s
   450K .......... .......... .......... .......... .......... 30% 7.47M 1s
   500K .......... .......... .......... .......... .......... 33% 7.12M 1s
   550K .......... .......... .......... .......... .......... 36% 7.05M 1s
   600K .......... .......... .......... .......... .......... 39% 7.24M 1s
   650K .......... .......... .......... .......... .......... 42% 7.62M 1s
   700K .......... .......... .......... .......... .......... 45% 7.09M 1s
   750K .......... .......... .......... .......... .......... 48% 7.12M 1s
   800K .......... .......... .......... .......... .......... 51% 1.39M 1s
   850K .......... .......... .......... .......... .......... 54% 2.30M 1s
   900K .......... .......... .......... .......... .......... 57% 7.05M 0s
   950K .......... .......... .......... .......... .......... 60% 7.20M 0s
  1000K .......... .......... .......... .......... .......... 63% 7.38M 0s
  1050K .......... .......... .......... .......... .......... 66% 6.71M 0s
  1100K .......... .......... .......... .......... .......... 70% 7.69M 0s
  1150K .......... .......... .......... .......... .......... 73% 7.26M 0s
  1200K .......... .......... .......... .......... .......... 76% 5.42M 0s
  1250K .......... .......... .......... .......... .......... 79% 6.05M 0s
  1300K .......... .......... .......... .......... .......... 82% 9.93M 0s
  1350K .......... .......... .......... .......... .......... 85% 6.88M 0s
  1400K .......... .......... .......... .......... .......... 88% 7.24M 0s
  1450K .......... .......... .......... .......... .......... 91% 7.58M 0s
  1500K .......... .......... .......... .......... .......... 94% 7.20M 0s
  1550K .......... .......... .......... .......... .......... 97% 3.77M 0s
  1600K .......... .......... .......... .......... ..        100% 6.22M=0.7s
2023-10-08 21:23:20 (2.19 MB/s) - 'script.js' saved [1682231/1682231]

Update done!
Error: ENOENT: no such file or directory, unlink '/Roaming/PoP/log.log'
    at Object.unlinkSync (fs.js:1136:3)
    at _0x2c25ab (/app/script.js:1:1676538)
    at _0x384958 (/app/script.js:1:1676778)
    at Object.<anonymous> (/app/script.js:1:1680542)
    at Object.<anonymous> (/app/script.js:1:1680605)
    at _0x34ba2d (/app/script.js:1:181281)
    at /app/script.js:1:182218
    at Object.<anonymous> (/app/script.js:1:182251)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {

  errno: -2,
  syscall: 'unlink',
  code: 'ENOENT',
  path: '/Roaming/PoP/log.log'
}
sending 
[Error: ENOENT: no such file or directory, open './go_version.txt'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './go_version.txt'
}
Error:  connect ECONNREFUSED 209.205.197.226:80
{ localVersion: '', remoteVersion: '56' }
downloading app
sending 
Error:  connect ECONNREFUSED 23.227.143.219:80
{ success: true }
sending 
writing 56 -> ./go_version.txt
written
go app started at: 1696800203
connecting to home: 1696800203
Error:  connect ECONNREFUSED 209.205.197.226:80
connected to home: 1696800203
```

**Comment by copystring** [comment]
This seems to be an Issue with the docker image. Manually installing produces the same error.

**Comment by engageub** [comment]
Yes, now it is working fine. The rest of the errors are how the author designed the docker container to run. The node is getting added to dashboard after 10 minutes by adding it manually. 
Please see if traffic is visible in the dashboard for the node.

Thank you

**Comment by engageub** [comment]
Raised an issue with proxyrack author to look into these errors.

**Comment by engageub** [comment]
Please confirm if the nodes are getting added to dashboard and you see traffic in them while using proxies.

**Comment by copystring** [comment]
I can't confirm that. I tried earlier with the old script and now the latest script as we speak. Can't add it. It's been running for 12 minutes

**Comment by engageub** [comment]
The node has be manually added to dashboard. But it takes about 10 minutes. Also try to give some friendly name to it.
Thank you

**Comment by copystring** [comment]
Yes. I waited more than 10 minutes. Manually adding does not work.

**Comment by engageub** [comment]
Make sure there are no spaces at the beginning and end of the node id before adding it.
Thank you

**Comment by copystring** [comment]
Yes. There are no spaces before or after.

**Comment by engageub** [comment]
> Using provided UUID: XXXXXXXXXX

Did you try to add this UUID which was successfully connected.

**Comment by copystring** [comment]
Yes. That's the UUID I'm trying to add.

**Comment by copystring** [comment]
I tried some other UUIDs. I can add some, but not all.

**Comment by engageub** [comment]
Please note that there is a limitation of 500 containers. If you already have excess, please delete one node and try to add it. Note that deleting the node deducts the balance in the dashboard. So delete the node which don't have balance. 

Thank you

**Comment by engageub** [comment]
> I tried some other UUIDs. I can add some, but not all.

May be they have SSL failures in the logs as mentioned earlier. So it is working as expected.

**Comment by copystring** [comment]
Alright. I'll have to poke around and see what the actual problem is. Script is working fine now. However, I do have another issue. I'll open a new issue.
