### ISSUE TITLE
EarnApp works until system is rebooted

### ISSUE THREAD

**Issue by copystring** [engageub/InternetIncome#56]
I forgot to say thanks for solving the other issue just now. So thanks for that.

Now the EarnApp issue.
EarnApp works just fine when initially setup, but once I reboot the computer it does not work anymore. Seems like it can't access the internet anymore.
It's marked as unhealthy in docker/portainer.
![image](https://github.com/engageub/InternetIncome/assets/1298861/f9015292-39a6-4ba1-8e77-e70ae21c1869)

For one of the EarnApp containers, I enabled logging.
```
███████╗░█████╗░██████╗░███╗░░██╗░█████╗░██████╗░██████╗░  ██████╗░░█████╗░░█████╗░██╗░░██╗███████╗██████╗░
██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔══██╗  ██╔══██╗██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗
█████╗░░███████║██████╔╝██╔██╗██║███████║██████╔╝██████╔╝  ██║░░██║██║░░██║██║░░╚═╝█████═╝░█████╗░░██████╔╝
██╔══╝░░██╔══██║██╔══██╗██║╚████║██╔══██║██╔═══╝░██╔═══╝░  ██║░░██║██║░░██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗
███████╗██║░░██║██║░░██║██║░╚███║██║░░██║██║░░░░░██║░░░░░  ██████╔╝╚█████╔╝╚█████╔╝██║░╚██╗███████╗██║░░██║
╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░░░  ╚═════╝░░╚════╝░░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝
An image by https://github.com/fazalfarhan01
Installing
✖ EarnApp was already started before.
2023-10-08 22:04:19.957 NOTICE: running PID: 20
2023-10-08 22:04:19.959 ERR: perr 05_svc_init {}
2023-10-08 22:04:19.961 ERR: perr init {}
2023-10-08 22:04:19.961 NOTICE: idle_state_monitor run
2023-10-08 22:04:19.966 NOTICE: run: E.start()
2023-10-08 22:04:19.966 NOTICE: devs changed: found 2 devs
2023-10-08 22:04:19.967 NOTICE: interface detected: tun0 (198.18.0.1)
2023-10-08 22:04:19.967 NOTICE: interface detected: eth0 (172.17.0.7)
2023-10-08 22:04:19.971 ERR: perr 10_show_dialog {}
2023-10-08 22:04:19.971 ERR: perr display {}
2023-10-08 22:04:19.982 NOTICE: run: E.update_consent(true)
2023-10-08 22:04:19.982 ERR: perr 15_choose_peer {}
2023-10-08 22:04:19.989 ERR: perr opt_in 
2023-10-08 22:04:19.998 NOTICE: perr lum_sdk_node_opt_in proxy 
2023-10-08 22:04:40.068 ERR: perr err [code=EAI_AGAIN] Error: getaddrinfo EAI_AGAIN perr.l-err.biz
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2023-10-08 22:04:40.070 NOTICE: perr send failed: H perr.l-err.biz P  R undefined E [code=EAI_AGAIN] Error: getaddrinfo EAI_AGAIN perr.l-err.biz
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2023-10-08 22:04:40.071 NOTICE: perr lum_sdk_node_opt_in proxy 
2023-10-08 22:04:40.080 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:05:00.102 ERR: perr err [code=EAI_AGAIN] Error: getaddrinfo EAI_AGAIN perr.l-agent.me
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2023-10-08 22:05:00.108 NOTICE: perr send failed: H perr.l-agent.me P  R undefined E [code=EAI_AGAIN] Error: getaddrinfo EAI_AGAIN perr.l-agent.me
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2023-10-08 22:05:00.109 NOTICE: perr lum_sdk_node_opt_in proxy 
2023-10-08 22:05:10.109 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:05:20.271 ERR: perr err [code=EAI_AGAIN] Error: getaddrinfo EAI_AGAIN perr.lum-sdk.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2023-10-08 22:05:20.271 NOTICE: perr send failed: H perr.lum-sdk.io P  R undefined E [code=EAI_AGAIN] Error: getaddrinfo EAI_AGAIN perr.lum-sdk.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2023-10-08 22:05:20.493 NOTICE: perr lum_sdk_node_opt_in proxy https://p45-32-1-201.l-agent.me:80/
2023-10-08 22:05:20.982 NOTICE: idle_state_monitor run
2023-10-08 22:05:40.367 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:06:10.762 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:06:20.293 ERR: perr err [code=ECONNRESET] Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2023-10-08 22:06:20.293 NOTICE: perr send failed: H perr.l-err.biz P https://p45-32-1-201.l-agent.me:80/ R undefined E [code=ECONNRESET] Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2023-10-08 22:06:20.315 NOTICE: perr lum_sdk_node_opt_in proxy https://p45-32-1-201.l-agent.me:80/
2023-10-08 22:06:21.986 NOTICE: idle_state_monitor run
2023-10-08 22:06:40.851 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:06:51.268 NOTICE: tun0 matched http://lumtest.com/myip.json
2023-10-08 22:06:51.271 NOTICE: dev tun0 connected
2023-10-08 22:06:51.272 NOTICE: device online: tun0, connecting...
2023-10-08 22:06:51.272 NOTICE: conn_open_single proxyjs.luminatinet.com:443 
2023-10-08 22:06:52.261 NOTICE: eth0 matched http://lumtest.com/myip.json
2023-10-08 22:06:52.261 NOTICE: dev eth0 connected
2023-10-08 22:06:52.261 NOTICE: device online: eth0, connecting...
2023-10-08 22:06:52.261 NOTICE: conn_open_single proxyjs.luminatinet.com:443 
2023-10-08 22:07:11.102 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:07:20.082 ERR: perr err [code=ECONNRESET] Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2023-10-08 22:07:20.082 NOTICE: perr send failed: H perr.l-agent.me P https://p45-32-1-201.l-agent.me:80/ R undefined E [code=ECONNRESET] Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2023-10-08 22:07:20.122 NOTICE: perr lum_sdk_node_opt_in proxy https://p45-32-1-201.l-agent.me:80/
2023-10-08 22:07:22.988 NOTICE: idle_state_monitor run
2023-10-08 22:07:41.206 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:08:11.653 ERR: ndt7 get config error: getaddrinfo EAI_AGAIN client.earnapp.com
2023-10-08 22:08:20.038 ERR: perr err [code=ECONNRESET] Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2023-10-08 22:08:20.039 NOTICE: perr send failed: H perr.lum-sdk.io P https://p45-32-1-201.l-agent.me:80/ R undefined E [code=ECONNRESET] Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2023-10-08 22:08:20.044 NOTICE: perr lum_sdk_node_opt_in proxy https://p155-138-230-221.l-agent.me:80/
2023-10-08 22:08:20.319 ERR: perr err [code=EPROTO] Error: write EPROTO 139886782007168:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
2023-10-08 22:08:20.320 NOTICE: perr send failed: H perr.l-err.biz P https://p155-138-230-221.l-agent.me:80/ R undefined E [code=EPROTO] Error: write EPROTO 139886782007168:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
2023-10-08 22:08:20.321 NOTICE: perr lum_sdk_node_opt_in proxy https://p155-138-230-221.l-agent.me:80/
2023-10-08 22:08:20.582 ERR: perr err [code=EPROTO] Error: write EPROTO 139886782007168:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
2023-10-08 22:08:20.593 NOTICE: perr send failed: H perr.l-agent.me P https://p155-138-230-221.l-agent.me:80/ R undefined E [code=EPROTO] Error: write EPROTO 139886782007168:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
2023-10-08 22:08:20.593 NOTICE: perr lum_sdk_node_opt_in proxy https://p155-138-230-221.l-agent.me:80/
2023-10-08 22:08:20.873 ERR: perr err [code=EPROTO] Error: write EPROTO 139886782007168:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
2023-10-08 22:08:20.873 NOTICE: perr send failed: H perr.lum-sdk.io P https://p155-138-230-221.l-agent.me:80/ R undefined E [code=EPROTO] Error: write EPROTO 139886782007168:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
2023-10-08 22:08:20.873 NOTICE: perr lum_sdk_node_opt_in proxy https://p164-90-133-59.l-agent.me:80/
2023-10-08 22:08:23.989 NOTICE: idle_state_monitor run
```

This seems to be a problem with dns resolving. `ping 8.8.8.8` works just fine, `ping google.de` does not work.

```
# ping google.de
ping: google.de: Temporary failure in name resolution
```

**Comment by engageub** [comment]
If you reboot the system, tun2socks configuration will not work. If you are using Socks5 Proxy with UDP support, this will not cause any issue on rebooting.

Thank you

**Comment by copystring** [comment]
OK. Is updating the proxies enough, or do I need to recreate all containers?

**Comment by engageub** [comment]
Yes, using updateProxies.sh script will make it work for now after reboot. 
Thank you

**Comment by engageub** [comment]
However, a permanent solution will still need to be required when reboot is done with HTTP proxies or proxies which don't support UDP. 
Thank you

**Comment by copystring** [comment]
I'll try with socks5 and then reboot. Not sure if my proxies support UDP, I'll try it anyway.

**Comment by engageub** [comment]
You will have to look into tun2socks logs after rebooting to see if your proxy supports UDP.
Errors will be shown if your proxy does not support UDP. 
Thank you

**Comment by engageub** [comment]
Code has been updated to support DNS on reboot. Please update and let me know if it works fine after reboot.

**Comment by copystring** [comment]
Yes! With the latest version and socks5 instead of http everything is still good after rebooting. Awesome! Thank you!

**Comment by engageub** [comment]
Thank you for the confirmation. Closing this issue. Feel free to reopen, if you still see any issues after rebooting.
